### PR TITLE
downgrade to jdk7

### LINKED ISSUE #21: Compile with Java 7
Saw this exception in an internal project:

```
Caused by: java.lang.UnsupportedClassVersionError: com/palantir/launchconfig/LaunchConfigPlugin : Unsupported major.minor version 52.0
    at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:71)
    at org.gradle.api.internal.plugins.DefaultPluginRegistry$1.load(DefaultPluginRegistry.java:51)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
```

Do you plan to support Java 7 with this plugin or do users need to run their Gradle builds with Java 8?

### PR DESCRIPTION
**Pull request by jmcampanini**
fixes #21

### CODE REVIEW

**Comment by jmcampanini** [comment]
@qinfchen + @zoubeiri + @ash211

planning on cutting a patch release (`0.3.4`) for this once i get a +1

**Comment by qinfchen** [comment]
can we add this the plugin checklist ?

**Comment by qinfchen** [comment]
👍

**Comment by jmcampanini** [comment]
good call. added. merging + releasing.

**Pull request merged**
